### ISSUE TITLE
Better support for Windows >= NT

### ISSUE THREAD

**Issue by s09bQ5** [twaugh/libieee1284#2]
This is just an outline of a solution, in case an ambitious Windows hacker happens to find this page.

As mentioned in [README.winNT](https://github.com/twaugh/libieee1284/blob/master/README.winNT) only a limited set of operations is supported with current Windows versions. With parallel ports becoming less and less common, chances are slim that Microsoft will extend the ParallelVdm driver to allow all features to be accessed from user space. The only solution is to access the hardware with another driver.

One driver that allows IO port access with current Windows versions is [InpOut32/InpOutx64](http://www.highrez.co.uk/Downloads/InpOut32/default.htm). But as the driver allows access to all IO ports from all applications, it is a security risk. This has f.ex. caused the [WinRing0 DLL to be revoked](https://translate.google.de/translate?hl=de&sl=ja&tl=en&u=https%3A%2F%2Fweb.archive.org%2Fweb%2F20131006062241%2Fhttp%3A%2F%2Fcrystaldew.info%2F2010%2F02%2F28%2Fwinring0-end%2F) by the author.

A driver like this is also not ideal because it misses the chance to use the [kernel space API](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/_parports/) to enumerate and synchronize access to parallel ports. This API is well documented and has been supported since Windows NT 3.5. ParallelVdm also makes use of it.

The ideal solution would
- find parallel ports using GUID_DEVINTERFACE_PARALLEL aka GUID_PARALLEL_DEVICE
- get the base address with IOCTL_INTERNAL_GET_PARALLEL_PORT_INFO
- get the high base address with IOCTL_INTERNAL_GET_PARALLEL_PNP_INFO (since Win2k)
- synchronize access with other drivers/apps using the IOCTL_INTERNAL_PARALLEL_PORT_ALLOCATE ioctl or the TryAllocatePort callback
- derive the ieee1284_capabilities from the HardwareCapabilities field (since Win2k)
- switch to and from bidirectional/ECP/EPP modes using IOCTL_INTERNAL_PARALLEL_SET_CHIP_MODE or the TrySetChipMode callback (since Win2k)
- get notified of interrupts using IOCTL_INTERNAL_PARALLEL_CONNECT_INTERRUPT (disabled in registry by default)
- return from ieee1284_get_irq_fd the handle of a manual-reset event [shared with the driver](http://www.osronline.com/article.cfm?id=108)
- speed up access with [Fast I/O dispatch](http://www.osronline.com/article.cfm?id=166) routines
- be signed with a certificate trusted by Windows

Useful code examples:
- https://github.com/s09bQ5/2430prg/tree/master/windows/driver (uses NT API)
- https://github.com/elitak/PPJoy (uses NT API and emulates it on Win98)
- https://github.com/s09bQ5/openparport/tree/master/src/paraccel/driver (speeds up ParallelVdm with Fast I/O)

**Comment by s09bQ5** [comment]
Closed? Why? I think that approach would still work with Windows 10.

**Comment by twaugh** [comment]
libieee1284 is no longer maintained. Let me know if you'd like to provide it a better home.

**Comment by mduggan** [comment]
Thanks for giving it a home for so long.  Sorry I never got around to a proper solution for Windows :)
