### ISSUE TITLE
Provide a Python 3 API

### ISSUE THREAD

**Issue by frsfnrrg** [twaugh/libieee1284#4]
Python 2 will no longer be supported in a year or two, so updating the python
interface to the Python 3 API would improve `libieee1284`. Attached is a set
of changes which ensure that the interface, at minimum, compiles and can
be loaded via `import libieee1284module`. (Importing as `libieee1284` will
require changing the installed module path.) Now C-string constants are
treated as Python byte strings; the Int->Long change has been applied,
and initialization of the module and `ieee1284.Parport` type both work
at first glance, although the details require more testing.

The change also, in my specific case, replaces compile flag `-I/usr/include/python3.6`
 with `-I/usr/include/python3.6m` ;  As you know your library far better than
I do, I leave you with all the work of adjusting Autotools so that the correct
Python version (or even both?) is chosen.

[delta.txt](https://github.com/twaugh/libieee1284/files/1822276/delta.txt)

**Comment by anatol** [comment]
I agree that libieee1284 should move to Python3. Python2 is end-of-life soon and many distros moving to Python3 as a default option.

**Comment by anatol** [comment]
Also master contains a number of python improvements and having a new release with the changes + python3 support is something the community needs.
